version: '3.7'

services:
  token_tracker-server:
    build:
      dockerfile: Dockerfile
      context: .
    user: "1000:1000"
    ports:
      - 10000:8000
    restart: unless-stopped
    container_name: token_tracker-server
    image: token_tracker-python
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --proxy-headers
    env_file: 
      - .env
    depends_on:
      - token_tracker-migrations
    volumes:
      - ./src:/app
    networks:
      token_tracker:
        aliases:
          - token_tracker-server

  token_tracker-monitor:
    build:
      dockerfile: Dockerfile
      context: .
    user: "1000:1000"
    restart: unless-stopped
    container_name: token_tracker-monitor
    image: token_tracker-python
    entrypoint: python -m app.monitor
    env_file: 
      - .env
    depends_on:
      - token_tracker-migrations
    networks:
      token_tracker:
        aliases:
          - token_tracker-monitor
  
  token_tracker-postgres:
    image: "postgres"
    container_name: token_tracker-postgres
    user: "1000:1000"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/data/postgres"
    volumes:
       - ./postgres:/data/postgres
    expose:
      - "5432"
    restart: unless-stopped
    networks:
      token_tracker:
        aliases:
          - token_tracker-postgres          

networks:
  token_tracker:
    external: true
